sudo: required
import: .travis-ci/shared.yml
before_install:
  - 'curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh'
  - 'chmod +x linux-install-1.10.1.466.sh'
  - 'sudo ./linux-install-1.10.1.466.sh'
  - 'curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo'
  - 'chmod +x install-clj-kondo'
  - 'sudo ./install-clj-kondo'
script:
  - 'npm run lint'
  - 'npm run compile-cljs-test && npm run cljs-test'